name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: mkdir -p ${{github.workspace}}/build; pushd ${{github.workspace}}/build; cmake ../; popd

    - name: build
      run: cmake --build ${{github.workspace}}/build
